// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'en'

export type Locales =
	| 'en'
	| 'ru'

export type Translation = {
	/**
	 * EN
	 */
	'language': string
}

export type TranslationFunctions = {
	/**
	 * EN
	 */
	'language': () => LocalizedString
}

export type Formatters = {}
